### ISSUE TITLE
The content seems to be of a different laboratory

### ISSUE THREAD

**Issue by edmundo096** [learn-co-students/js-basics-online-shopping-lab-cb-gh-000#8]
Seems that the lab now talks about a "Time complexity" project instead of the Online shoping as in the https://learn.co/tracks/full-stack-community-bootcamp/javascript-foundations/data-structures/online-shopping-lab

The Open button downloads this "Time complexity" but running `learn` states `This directory doesn't appear to have any specs in it. `

**Comment by philoniare** [comment]
**Issue confirmed**
Had to manually create the `package.json` and `index.js` to start running the tests.

**Comment by gj** [comment]
Hi @edmundo096 and @philoniare !

Sorry for the mixup — lab should be good to go now!
